name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: python -m pip install --upgrade pip build twine
      - run: python -m build
      - run: twine check dist/*
      - run: pip install dist/*.whl
      - run: python -c "from modelit import perceptron; print(perceptron.__name__)"
